### ISSUE TITLE
Did  you test the speed in IOS. Thanks!

### ISSUE THREAD

**Issue by camel007** [thtrieu/yolotf#2]

**Comment by thtrieu** [comment]
on iPhone 6, the speed for tiny YOLO is 3-4 fps, this can be due to my lack of experience with iOS devices (post-processing the prediction value, drawing bounding boxes, displaying them v...v...). I suggest you give it a try.

**Comment by camel007** [comment]
Thanks for your reply!
 I'm trying to binary yolo weights, and then Migrate it to mobile device!

**Comment by jeffxtang** [comment]
@thtrieu Can you share your test iOS code (post-processing the prediction value, drawing bounding boxes, displaying them)? 

I'm able to use the same tiny-yolo-voc.pb, which when used with "flow --pbLoad built_graph/tiny-yolo-voc.pb --metaLoad built_graph/tiny-yolo-voc.meta --imgdir img" can generate good result, in my test iOS project and get the output tensor with the same size (21125) as the net_out's shape (1x13x13x125) in yolov2/predict.py's postprocess, but the values in the iOS output tensor is different from the Python net_out value (on the same input image). Should I expect the two values to be the same? I haven't ported the Python post processing code to iOS yet..

Thanks!

**Comment by jeffxtang** [comment]
I got my tested iOS code in a new repo https://github.com/jeffxtang/yolov2_tf_ios.. Thanks for the nice Darkflow repo without which I'd certainly not be able to make it..
