### ISSUE TITLE
interpreting decode()

### ISSUE THREAD

**Issue by MarcGroef** [thtrieu/yolotf#4]
Thanks for sharing this awesome project :)

I'd like to fork this repo for a research project, to experiment with yolo, using alternative input types (multiple different spectral range images, e.g.). 

I tried a tf implementation myself, though I got stuck on the error definition, regarding the bounding boxes error definition..
It seems you solved this problem, using numpy operations, though I don't quite follow your steps.
As far as I understand you perform these operations in decode(), tfnet.py, r140.

I wondered whether you could add come comments in decode(), explaining your solution.
Some statements as r169 are a bit magical to me :)
I'd like to fully understand your steps, so I could modify your code if necessary.

May the force be with you,

Marc

**Comment by thtrieu** [comment]
@MarcGroef I am so so so looking forward to your modifications (for better arrangement of code, efficiency, etc). Cheers for taking the time to look at my code.

First, the loss calculation is not only done in decode() - which uses the network output and placeholders' value to calculate the loss, it starts from the moment minibatches of data are yielded by data.py. I added a lot of comments, please refer to the comment in data.py as well as decode() to understand my approach to calculating YOLO's loss.

Again, I expect my solution to your problem you are stucking at is not the best solution, so I hope you can move on to a better one from mine.

**Comment by MarcGroef** [comment]
I'll look into it!
Thanks for the response :+1: 

Cheers,
