### ISSUE TITLE
Random scale/translate send object(s) out of bound

### ISSUE THREAD

**Issue by EngShaheen** [thtrieu/yolotf#7]
while trainig on my data
I got this error
**Random scale/translate send object(s) out of bound**
as shown in the image
and then it starts to test on the testing data and store the results to `results/` folder

I think the model doesn't do the training phase properly 
and the problem is in the `shuffle` function in `TFnet.py` file
in the **try** statement it has some error and goes to the **except** 
any I deas about this error?
![issue](https://cloud.githubusercontent.com/assets/16343109/20103605/62e9325c-a5d3-11e6-80de-b63537fe1927.JPG)

**Comment by thtrieu** [comment]
Dear @EngShaheen you are using an old version of this repo, please update and tell me if it works or not. If the problem is still there, please give me exact steps to reproduce the problem, including dataset & annotation you are using.

**Comment by EngShaheen** [comment]
Thanks for your reply
I've just cloned a new version of this repo and tried again but I got another error
![tf](https://cloud.githubusercontent.com/assets/16343109/20245418/f8445276-a9a9-11e6-966f-6dd88aa778fd.JPG)

I am using two classes 
`infected
good`
I think I have parsed them successfully
![dataset](https://cloud.githubusercontent.com/assets/16343109/20245447/8d732822-a9aa-11e6-876a-57d0df08ce81.png)

also, I think I have initialized weights successfully
![weights](https://cloud.githubusercontent.com/assets/16343109/20245612/ac0ea664-a9ad-11e6-8cf9-a75515386a14.png)

**Comment by thtrieu** [comment]
I suspect you are using --savepb and --train options at the same time? If so, please finish training first before using --savepb in combination with --load option, because --savepb will disable every variable inside the network and turn them into constants, so that the resulting protobuf file will contain a constant graph. 

Best of luck :)

**Comment by EngShaheen** [comment]
That's right , I was setting the flag of --savepd to be True
now, I set it to False 
but I got another error 
![epoch](https://cloud.githubusercontent.com/assets/16343109/20246034/d02ac376-a9b6-11e6-8955-4c3cbf29e8e5.JPG)
I really appreciate your effort

**Comment by thtrieu** [comment]
Well this time I cant really say the fault is on my side. I believe the image the program is trying to read does not exist. Try printing out `imPath` before doing anything in yolo/drawer.py/yolo_preprocess() and make sure that path does pointing to an image.

**Comment by EngShaheen** [comment]
I printed the image path and it's correct except that the extension of the image is written in small letters `.jpg`, and all the extensions of the images in my dataset are in capital letters `.JPG`
here is a picture for the `imPath`
![path](https://cloud.githubusercontent.com/assets/16343109/20246296/72038cc8-a9bc-11e6-9e9e-519653dfe89b.JPG)

here is a picture for the extension of my dataset
![data](https://cloud.githubusercontent.com/assets/16343109/20246308/c6f876c6-a9bc-11e6-92e3-41a9c4b0c4fc.JPG)

is it case sensitive ? is there an easy way to change the parsing somehow, instead of doing it the hard way and renaming all my +1000 images in the dataset?

**Comment by thtrieu** [comment]
well, I didn't know cv2 imread is case insensitive, I updated the code, please try again

**Comment by EngShaheen** [comment]
thank you very much for you help
I suppose it is working now 👍 
![success](https://cloud.githubusercontent.com/assets/16343109/20246829/1265a862-a9c8-11e6-8c03-b9b40b7ee513.JPG)

but you should add 
`import os`
at the beginning of the `yolo/drawer.py` file

also, I suggest that you mention in the readme file that the annotation of the data should be the same format of the PASCAL data (**xml file**) 
and there is a tool to annotate the data is called **labelimg** that output the same format

and also, I suggest that you make a default folder inside the repo for the innotation, training data and testing data 

Have a nice day

**Comment by thtrieu** [comment]
cool ! thanks for your suggestions, lots of work to be done :)

**Comment by thtrieu** [comment]
@EngShaheen By the way, I think I figured a better way to do it than patching the error directly inside drawer.py. To avoid future errors, you may want to save the current state of training, pull the new code and re- clean.py and train again. Good luck.

**Comment by EngShaheen** [comment]
I see that the latest update will work for Pascal annotation. But unfortunately, it will not work for my annotation
because in my annotation in `<filename>` the extension of the file is not there 
Here is a screenshot for my annotation
![filename](https://cloud.githubusercontent.com/assets/16343109/20247462/6de38670-a9d5-11e6-83fa-d549bb3bd91e.JPG)
Good Luck
