### ISSUE TITLE
OSError: [Errno 2] No such file or directory: '../pascal/VOCdevkit/ANN'

### ISSUE THREAD

**Issue by Yaffa1607** [thtrieu/yolotf#8]
When I run python clean.py  I get this error :  OSError: [Errno 2] No such file or directory: '../pascal/VOCdevkit/ANN'

I assume the ANN folder might've been already downloaded with the repo , but couldnt find it

**Comment by thtrieu** [comment]
If you read README, the full syntax to parse annotation should be `python clean.py /path/to/annotation/folder`. `../pascal/VOCdevkit/ANN` is simply the default one on my machine, please specify your own.

**Comment by Yaffa1607** [comment]
Thank you . Can you elaborate on the final format for the training txt file. 
I have a txt file that is as follows: 

/path/to/image x1 y1 w h 

What is the x1 ratio?

**Comment by thtrieu** [comment]
Well the format must be the same with Pascal VOC dataset format of annotation. Please check the Pascal VOC website for precise description (or simply download the dataset and look at .xml files in the annotation folder).
